version: 0.0
os: linux
files:
   - source: /web
     destination: /var/www/html
   - source: /
     destination: /tmp/codeDeploy
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
   - object: /tmp/codeDeploy
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: /touch_scripts/touch_file_1.sh
    - location: /httpd_scripts/install_apache.sh
    - location: /httpd_scripts/start_apache.sh
   AfterInstall:
    - location: /httpd_scripts/restart_apache.sh

