version: 0.0
os: linux
files:
   - source: /web
     destination: /var/www/html
files:
   - source: /
     destination: /tmp
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
   - object: /tmp
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:

    - location: /tmp/httpd_scripts/install_apache.sh
    - location: /tmp/httpd_scripts/start_apache.sh
   AfterInstall:
    - location: /tmp/httpd_scripts/restart_apache.sh

